### ISSUE TITLE
vlist not listing certain venoms

### ISSUE THREAD

**Issue by slester** [svof/svof#67] opened 2015-09-06 20:38 UTC
vlist (with scripts off)

```
Vial                    Venom                          Doses    Months   
-------------------------------------------------------------------------------
Hazelwood vial409851    the venom aconite              150      117
Ebony vial473453        the venom aconite              150      118
Ebony vial473676        the venom epteth               150      118
Ebony vial473682        the venom epteth               150      118
Applewood vial403466    the venom delphinium           150      117
Gold-trimmed ceramic vi the venom delphinium           150      149
Gold-trimmed ceramic vi the venom epseth               150      149
Gold-trimmed ceramic vi the venom epseth               150      149
Gold-trimmed ceramic vi the venom delphinium           150      149
Gold-trimmed ceramic vi the venom epseth               150      149
Gold-trimmed ceramic vi the venom epseth               150      149
Gold-trimmed ceramic vi the venom delphinium           150      149
Gold-trimmed ceramic vi the venom epseth               150      149
Gold-trimmed ceramic vi the venom epseth               150      149
-------------------------------------------------------------------------------
```

with scripts on:

```
vlist
Vial                    Venom                          Doses    Months   
-------------------------------------------------------------------------------
Gold-trimmed ceramic vi the venom delphinium           150      149
Gold-trimmed ceramic vi the venom epseth               150      149
Gold-trimmed ceramic vi the venom epseth               150      149
Gold-trimmed ceramic vi the venom delphinium           150      149
Gold-trimmed ceramic vi the venom epseth               150      149
Gold-trimmed ceramic vi the venom epseth               150      149
Gold-trimmed ceramic vi the venom delphinium           150      149
Gold-trimmed ceramic vi the venom epseth               150      149
Gold-trimmed ceramic vi the venom epseth               150      149
-------------------------------------------------------------------------------
o 7035h(100%) 7045m(100%) 100%e 100%w exdb- ( ) 13:38:32.584 d|s 
(svof): Elixirs:
  3 an elixir of speed (547s)                             
 10 an elixir of mana (1846s)                             
  3 an elixir of levitation (558s)                        
 10 an elixir of health (1880s)                           
  3 an elixir of venom (597s)                             
  3 an elixir of frost (598s)                             
  3 an elixir of immunity (572s)                          
(svof): Salves:
  3 a salve of restoration (600s)                         
  6 a caloric salve (1175s)                               
  5 a salve of mass (979s)                                
  3 an epidermal salve (559s)                             
  3 a salve of mending (538s)                             
(svof): Empties:
  1 empty (0s)                         1 short            
(svof): Venoms:
  2 the venom aconite (300s)                              
  2 the venom epteth (300s)                               
  1 the venom delphinium (150s)        1 short            
  0 the venom epseth (0s)              2 short            
  (change desired amounts)
  (append refill request, need 4 refills)
  (refill from tuns, need 4 refills)
```

**Comment by vadi2** [comment] 2015-09-06 21:25
The issue is the bug in the in-game elist that is cutting off vial ID's.

**Comment by jgh713** [comment] 2016-07-26 23:37
Best way would be to split this into two separate triggers and base the triggers on length, since they're different (for some god-awful reason). Elist is 25 chars prior to the elixir name, without forcing a space. Vlist is 23 chars prior to the venom name, with a force space afterwards.

**Comment by QwindorRousseau** [comment] 2019-07-15 08:29
This was fixed already and left open. Closing it.

**Closed by QwindorRousseau** 2019-07-15 08:29 UTC
Labels: bug, futher analysis needed, up for grabs
