### ISSUE TITLE
Wild Staff and Flail staff repeating

### ISSUE THREAD

**Issue by rzer0knight** [svof/svof#372] opened 2019-02-16 10:27 UTC
Hello,

I think the lines for flail and wield quarterstaff has been changed, because the system keeps spamming trying to wield and flail them. It stops after i FLAIL STAFF manually. If this is the case, how do I find the new lines and send them to you?

Thanks

I've attached a screen of the issue.

![sylverror](https://user-images.githubusercontent.com/26971393/52898428-b6dc3700-3218-11e9-8b79-c567b437eb2d.png)

**Comment by DazedxJoker** [comment] 2019-02-18 16:29
That looks like it might be command separator issue. Unless your staff isn't a "quarterstaff"

**Comment by rzer0knight** [comment] 2019-02-21 14:18
I am using a Quarterstaff. Any idea how to fix this?

**Comment by QwindorRousseau** [comment] 2019-07-15 09:29
@rzer0knight was this because of the commandseperator issue that we fixed?

**Comment by DazedxJoker** [comment] 2019-07-23 04:47
Asked for help to replicate this to no avail:

https://ada-young.appspot.com/pastebin/cOpzAM1N

Closing for now, if it resurfaces we shall deal with it.

**Comment by druque** [comment] 2019-07-26 16:05
I can reproduce this one on Sylvan.

With only one staff in inventory:
![1staff](https://user-images.githubusercontent.com/9988184/61965096-5de2ad00-afc7-11e9-90b8-bd60be7184ac.png)
all works as it should

With 2 staves:
![2staff](https://user-images.githubusercontent.com/9988184/61965118-6509bb00-afc7-11e9-9b63-048669c63621.png)
System spams until you put the other staff in your pack.

Sylvans usually have a spare staff because if you plant one, you lose it.

**Comment by DazedxJoker** [comment] 2019-07-26 19:43
Looks like the def up line isn't in properly. Only the already deffed line. And unwielding removes the , so you never get that line with 2 in the inventory

**Comment by K1ngSpad3z** [comment] 2019-07-27 16:07
Okay so I went through this. defs_data is all correct, however there wasn't an actions part in the dict for using the flail staff, so svo never recognized the action. I don't have a forestal to test this but if someone does, then try these changes. Go into the script Dictionary of actions (affs/defs/misc), and on line 12461 add the following

actions = {"flail quarterstaff"}

Save the profile and restart mudlet and see if that affects anything for defing up flail

**Closed** 2019-07-27 16:22 UTC
Labels: Possible fix included, futher analysis needed, in-client, simple difficulty
