### ISSUE TITLE
QWC reports everyone as rogue

### ISSUE THREAD

**Issue by ellefanning** [svof/svof#225] opened 2016-08-20 04:09 UTC
qwc will report everyone as rogue.

if you use vconfig to turn off autochecking and turn it back on and set will use honours, svof will rescan nameDB. During the scan, svof will properly place scanned targets into their respective orgs with qwc. once the scan completes, qwc will revert back to showing everyone as rogue.

**Comment by keneanung** [comment] 2016-08-20 08:15
You need to turn MXP off both in game (`config mxp`) and in mudlet (advanced options -> force mxp negotiation off).

If that doesn't help, it's a known issue for some people with unclear reasons, sadly.

**Comment by keneanung** [comment] 2016-09-09 14:10
Possible duplicate of #166

**Comment by keneanung** [comment] 2016-09-15 07:31
Closing this as duplicate.

**Closed by keneanung** 2016-09-15 07:31 UTC
Labels: bug, duplicate, futher analysis needed
