### ISSUE TITLE
Consider turning off ppl tracker on slow pcs

### ISSUE THREAD

**Issue by keneanung** [svof/svof#167] opened 2016-03-22 16:24 UTC
See http://forums.achaea.com/discussion/comment/292982/#Comment_292982 and following for a discussion

**Comment by jgh713** [comment] 2016-07-26 21:47
This is a duplicate of #133

**Comment by jgh713** [comment] 2016-11-24 23:38
Closing, duplicate.

**Closed by jgh713** 2016-11-24 23:38 UTC
Labels: enhancement, futher analysis needed, medium priority, up for grabs
