### ISSUE TITLE
Curing Defenses not being removed on class switch

### ISSUE THREAD

**Issue by impuxi** [svof/svof#340] opened 2018-01-30 07:36 UTC
Switched from Monk to Runewarden and got spammed with trying to put up the toughness defense. Only seems to be an issue when CURING DEFENCES ON

**Comment by vadi2** [comment] 2018-01-30 19:46
They are removed though, see `vshowd`. I'm guessing in-game serverside curing system is the one that's spamming them?

**Comment by DazedxJoker** [comment] 2018-01-31 09:23
Yea, I believe the issue is that they are being left on serverside defence keepup on class change.

**Comment by vadi2** [comment] 2018-01-31 09:28
Seems to me that serverside shouldn't be putting up defences you don't have, tho?

We'll add a workaround to the system of course.

**Comment by vadi2** [comment] 2018-01-31 17:03
So that's the easy fix for this? `CURING PRIORITY RESET`?

**Comment by vadi2** [comment] 2018-02-04 04:51
Thanks to Atakrez for pointing out `curing priority defense list reset` - fixed with https://github.com/svof/svof/pull/329/commits/b6242a3a734571c88af6833bad3584559cf0ba26

**Closed by vadi2** 2018-02-04 04:51 UTC
