### ISSUE TITLE
Afflictions incorrectly adding to table

### ISSUE THREAD

**Issue by Zekeros** [svof/svof#332] opened 2018-01-22 09:18 UTC
`"[string "Script: Setup"]:1213: svo.addaff: what aff would you like to add? name must be a string"
`

This line gets repeated whenever I gain an affliction

**Comment by vadi2** [comment] 2018-01-22 09:24
Is it like this always when you start the system or after something happens?

**Comment by Zekeros** [comment] 2018-01-22 09:50
It doesn't happen until I gain a new affliction. For example when I start bleeding it happens once on every bleed line, or if I sleep it happens when I first go to sleep but then not again. There's two `(e!)`'s at the beginning of the prompt when I go to sleep, then only one if I trigger the `You are asleep and can do nothing. WAKE will attempt to wake you.` but there isn't on the lines of my dream. Should I post a screenshot, this all sounds really confusing.

**Comment by vadi2** [comment] 2018-01-23 13:32
The fix by @CorTheWin is available here: https://github.com/svof/svof/blob/gh-pages/testing/Svof.v33.2.zip

Automatic update doesn't work yet, so you'll need to manually uninstall the old modules and install the new one.

**Comment by Zekeros** [comment] 2018-01-23 15:50
```
"[string "Script: Curing skeleton"]:1293: table index is nil"

[KALMIA] You secrete kalmia and deftly bring an iron dirk to your mouth, letting the venom drip upon
it.
[CURARE] You secrete curare and deftly bring an iron dirk to your mouth, letting the venom drip upon
it.
You quickly prick Syndra with your dirk.
The attack rebounds back onto you!
Striking like a snake, you prick Syndra a second time with your dirk.
The attack rebounds back onto you!
A prickly stinging overcomes your body, fading away into numbness.
97% | 2631h, 3102m, 12045e, 13000w e[par]- 
[Curing]: OUTR MAGNESIUM
You remove 1 magnesium, bringing the total in the rift to 48. (0.312s)
97% | 2631h, 3102m, 12045e, 13000w e[par]- 
[Curing]: EAT MAGNESIUM
You eat a magnesium chip.
Your muscles unlock; you are no longer paralysed.
97% | 2631h, 3102m, 12045e, 13000w e- 
```

The prompt is now listing what I have but the error line has changed with the new update 33.2

**Comment by CorTheWin** [comment] 2018-01-23 19:28
Can you give any more information? (does it happen every time you get an aff? only on certain affs? etc)

**Comment by Zekeros** [comment] 2018-01-24 10:01
It happens every time I get any affliction as far as I can tell, and it happens on every affliction

**Comment by impuxi** [comment] 2018-01-30 07:33
I'm still getting this when I get proned:

"[string "Script: Curing skeleton"]:1293: table index is nil"

**Comment by DazedxJoker** [comment] 2018-01-30 18:20
Happens every affliction, looks like it is occurring when the system creates a stopwatch to keep track of how long you have an affliction

**Comment by vadi2** [comment] 2018-01-30 19:55
I'm not getting the same:

```
4600h, 4730m, 21900e, 20400w ex-vaff paralysis
(outr bloodroot|eat bloodroot)
You remove 1 bloodroot leaf, bringing the total in the rift to 91.
You eat a bloodroot leaf. (0.191s)
4600h, 4730m, 21900e, 20400w ex-
You may eat another plant or mineral. (1.625s)
```

How can I reproduce this?

**Comment by DazedxJoker** [comment] 2018-01-31 07:19
vaff doesn't seem to reproduce the error. However getting actually afflicted in the game by someone seems to trigger it fairly reliably.

**Comment by vadi2** [comment] 2018-01-31 08:54
Fixed with https://github.com/svof/svof/pull/329/commits/642fdfb280e5d96efe51bfea48cd85d4bd9779b5.

New beta, [33.3](https://github.com/svof/svof/raw/gh-pages/testing/Svof.v33.3.zip), has this fix.

**Closed by vadi2** 2018-01-31 08:54 UTC
