### ISSUE TITLE
Capturing city enemies needs updating

### ISSUE THREAD

**Issue by ndsamuelson** [svof/svof#807] opened 2023-03-05 04:23 UTC
I was helping someone fix their triggers for city enemy capture since conquest has changed the actual names of the cities to no longer necessarily have 'City' in the name. I will fiddle with it when I learn what the other ones are and make sure I can actually get it working. 
For the record, Hashan's is no longer the City of Hashan, it is                      Enemies of the Starforged Nation of Hashan:

Eleusis' hasn't changed yet, and I can only guess at the others or actually run around and look at each of them. Either way I know the script will need to be re-worked slightly since it's assuming everything not city or order is a house.

**Comment by DazedxJoker** [comment] 2023-03-05 14:04
Here's the ones I could access. 

Enemies of the Tyrannical Territories of Mhaldor:
Enemies of the Shining Territories of Targossas:
Enemies of the City of Eleusis:
Enemies of the Dread Nation of Ashtan:
Enemies of the Just Territories of Cyrene:

**Comment by TheLastDarkthorne** [comment] 2023-03-05 19:05
The problem is that it changes depending on how much territories they got, and probably changed back and forth as they gain/lose... It is probably easier just to check if the name of the city is in the string lol

**Comment by ndsamuelson** [comment] 2023-03-06 04:37
> The problem is that it changes depending on how much territories they got, and probably changed back and forth as they gain/lose... It is probably easier just to check if the name of the city is in the string lol

That was sort of my approach in my head. Rather than searching for 'City' search for Hashan or Mhaldor etc.

**Comment by TheLastDarkthorne** [comment] 2023-03-07 16:12
If you can test #808 and see if it works on your system it would be good :)

**Comment by TheLastDarkthorne** [comment] 2023-03-18 17:01
Closing this as it was sorted out already

**Closed as completed by TheLastDarkthorne** 2023-03-18 17:01 UTC
