### ISSUE TITLE
Error in notifypriodiffs on class change

### ISSUE THREAD

**Issue by DazedxJoker** [svof/svof#341] opened 2018-01-31 09:21 UTC
[  LUA  ] - object:<error in anonymous Lua function> function:<no debug data available>
            <Lua error:[string "Script: Serverside"]:438: attempt to index field '?' (a nil value)>

**Comment by vadi2** [comment] 2018-01-31 17:01
I'm not getting this error on 33.3, are you?

**Comment by DazedxJoker** [comment] 2018-01-31 17:33
Yes, I am

**Comment by vadi2** [comment] 2018-02-01 08:35
Was that there before?

**Comment by DazedxJoker** [comment] 2018-02-01 08:43
No it wasn't.

**Comment by vadi2** [comment] 2018-02-01 13:46
OK, I'll have a look at the serverside thing.

@CorTheWin is looking into the duplication.

If we keep it one issue per issue, it'll be easier to have a conversation about them and not get confused

**Comment by vadi2** [comment] 2018-02-01 19:58
I think for the most part this is a change in the game... does the original svof have this?

Because it's doing things like 'curing priority hamstring 26' whereas the game refers to it as hamstrung, and svof's dict does not have 'hamstrung' as the gamename for hamstring.

**Comment by DazedxJoker** [comment] 2018-02-01 20:19
I'm not able to replicated it in svof 33.

**Comment by vadi2** [comment] 2018-02-02 07:51
Yep, okay. I've spent a couple of hours on it this morning and it seems the issue is in `svo.sk.getafterstateprios()` and it's `before` equivalent that have non-affs/defs bundled in the `slowcuring` balance for whatever reason.

**Comment by vadi2** [comment] 2018-02-03 15:48
Fixed with https://github.com/svof/svof/pull/329/commits/de1a232d129b05279c205e7b385b4922f6407943

**Closed by vadi2** 2018-02-03 15:48 UTC
