### ISSUE TITLE
Vdefup fortifyall

### ISSUE THREAD

**Issue by seriley** [svof/svof#75] opened 2015-09-20 22:32 UTC
When setting fortifyall using VDEFUP, mudlet goes into a continuous loop when I subsequently use VDEFS BASIC, since svo.defc.fortifyall is never set true.

Removing from defup and entering FORTIFY ALL at the command line, individual channels are fortified, but the fortifyall flag is not set.

**Comment by keneanung** [comment] 2015-10-13 09:21
Seems to be a duplicate of #47

**Closed** 2015-12-15 13:24 UTC
