### ISSUE TITLE
System parrying Error/Lag spam.

### ISSUE THREAD

**Issue by Taryius** [svof/svof#335] opened 2018-01-24 06:00 UTC
Pardon lack of coding terminology on my end,

With the system parrying on (vconfig parry - (svof): Will make use of parry. ) the system spams out with the following error on every prompt: (e!)(e!)(e!)(svof): Warning, lag detected (while doing/curing doparry)

It is also not displaying any error when you click the blue (e!).

I didn't notice any functional issues with the parrying, though I wasn't able to test the lasthit/oppositelasthit strategies.

I found the error line here,

[ERROR:] object:<error in Lua code> function:<no debug data available>
         <Lua error:[string "echo("The problem was: doparry failed to start ([string "Script...
"]:1: ')' expected near 'Script'>

Persists through reconnect and restarting mudlet.

The error completely stops showing up if you config parrying of with 'vconfig parry manual'.

**Comment by DazedxJoker** [comment] 2018-01-24 06:53
This may also be relevant: 
pll
[  LUA  ] - object:<(p*) Set parry manually> function:<Alias165>
            <[string "Script: Parry"]:258: attempt to index field 'parry_shouldbe' (a nil value)>

**Comment by DazedxJoker** [comment] 2018-01-29 23:13
I've worked around this issue by copy and pasting my sp_config file from one profile to the other, the issue is caused by 

svo.sp_config returning {}

**Comment by vadi2** [comment] 2018-01-31 16:39
Fixed with https://github.com/svof/svof/pull/329/commits/a91f3f7daa452089e7447d8b03e05087e9c36654.

**Closed by vadi2** 2018-01-31 16:39 UTC
